drop table defense;
CREATE TABLE DEFENSE(	
  PLAYER VARCHAR(200) NOT NULL, 
	TEAM VARCHAR(200) NOT NULL, 
	INT FLOAT(10), 
	YARDS FLOAT(10), 
	AVG FLOAT(10), 
	LG FLOAT(10), 
	TD FLOAT(10), 
	TACKLES FLOAT(10), 
	SACK FLOAT(10), 
	YEAR FLOAT(10) NOT NULL, 
  POS VARCHAR(200), 
	POSITIONTYPE VARCHAR(200), 
  PRIMARY KEY (PLAYER, TEAM, YEAR)
);

drop table passing;
CREATE TABLE PASSING(	
  PLAYER VARCHAR(200) NOT NULL, 
	TEAM VARCHAR(200) NOT NULL, 
	ATT FLOAT(10), 
	CMP FLOAT(10), 
	PCT FLOAT(10), 
	YDS FLOAT(15), 
	YPA FLOAT(10), 
	TD FLOAT(10),
  INT FLOAT(15),
	LG FLOAT(10), 
	SACK FLOAT(10), 
	YEAR FLOAT(10) NOT NULL, 
  POS VARCHAR(200), 
  POSITIONTYPE VARCHAR(200), 
  PRIMARY KEY (PLAYER, TEAM, YEAR)
);

drop table receiving;
CREATE TABLE RECEIVING(	
  PLAYER VARCHAR(200) NOT NULL, 
	TEAM VARCHAR(200) NOT NULL, 
	REC FLOAT(10), 
	YDS FLOAT(15), 
	YPG FLOAT(10), 
	LG FLOAT(10),  
	TD FLOAT(10),
	YEAR FLOAT(10) NOT NULL, 
  POS VARCHAR(200), 
  POSITIONTYPE VARCHAR(200), 
  PRIMARY KEY (PLAYER, TEAM, YEAR)
);

drop table rushing;
CREATE TABLE RUSHING(	
  PLAYER VARCHAR(200) NOT NULL, 
	TEAM VARCHAR(200) NOT NULL, 
	YDS FLOAT(15), 
	YPG FLOAT(10), 
	LG FLOAT(10),  
	TD FLOAT(10),
	YEAR FLOAT(10) NOT NULL, 
  POS VARCHAR(200), 
  POSITIONTYPE VARCHAR(200), 
  PRIMARY KEY (PLAYER, TEAM, YEAR)
);


